services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: linear-postgres
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=linear
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
